### PR TITLE
feat: Added workflows

### PR DESCRIPTION
**Pull request by ashikka**
Closes issue #39

### CODE REVIEW

**Comment by alias-rahil** [comment]
Hey @ashikka thanks for the PR, Can you tell what all env variables I need to set for this workflow to run? Also, is there any way I can test it without merging first?

**Comment by ashikka** [comment]
> Hey @ashikka thanks for the PR, Can you tell what all env variables I need to set for this workflow to run? Also, is there any way I can test it without merging first?

Hi! Yeah, you need to generate and add an `NPM_PUBLISH_TOKEN` to your secrets. I believe when you published the package on the npm registry you would have been provided with one. Please check. 

Furthermore, I can change the action branch name from `master` to `dev`, then you can test it. But do keep in mind that the changes would reflect in the npm registry.

**Comment by alias-rahil** [comment]
> Furthermore, I can change the action branch name from `master` to `dev`, then you can test it. But do keep in mind that the changes would reflect in the npm registry.

Yes please, change the target branch to dev too

**Comment by alias-rahil** [comment]
Hey @ashikka, the workflow is trying to publish v18.10.0 but it already exists. There is some error, can you check? I invited you as a contributor to the repo

**Comment by alias-rahil** [comment]
Great work @ashikka! Looks good to me! ✨

**Comment by ashikka** [comment]
> Hey @ashikka, the workflow is trying to publish v18.10.0 but it already exists. There is some error, can you check? I invited you as a contributor to the repo

Yup, fixed that.

**Comment by alias-rahil** [comment]
Thanks again @ashikka! Everything works well ✨

**Pull request merged**
