### PR TITLE
There are 4 changes a.)Having the app launch in full-screen using chr…

### PR DESCRIPTION
**Pull request by Vishal-sys-code**
1.) Having the app launch in full-screen "app mode" using Chrome for Android’s "Add to home screen" menu item.
2.) Dark Mode
      One issue:- _The GitHub logo in the footer is being hidden whenever we will toggle the dark mode._
3.) Function for Avoiding losing text when refreshing the browser with local storage
     Explanation:- _Whenever we write the in the text area suppose we want to do it after some hours the written part in it will be 
                           disappear and also when we refresh the browser too, so I have added a function so that the user can have the 
                           text in its local storage until it changes. The benefit for this will be he will not lose any data after having an 
                           emergency condition_.
4.) Smooth Scrolling.

### CODE REVIEW

**Comment by alias-rahil** [comment]
Can you deploy the changes at https://vishal-sys-code.github.io/handwritten.js for me to see a preview?

**Comment by Vishal-sys-code** [comment]
Sure...
Link:- https://vishal-sys-code.github.io/handwritten.js/

**Comment by alias-rahil** [comment]
Looks good to me. Do you have any fix for this?

> One issue:- _The GitHub logo in the footer is being hidden whenever we will toggle the dark mode._

**Comment by Vishal-sys-code** [comment]
I'm doing something for this logo. Give me 18 hours to fix this.

**Comment by alias-rahil** [comment]
> Give me 18 hours to fix this.

Oddly specific xD, sure take your time :)

**Comment by Vishal-sys-code** [comment]
I have made a change for the logo the link of the deployment is given below. 

Link: https://vishal-sys-code.github.io/handwritten.js/ 

The logo is safe now after toggling the dark mode. Can you see it?
Hope you like it.

**Review by alias-rahil — APPROVED** [review]
LGTM ✰

**Comment by alias-rahil** [comment]
@all-contributors please add @Vishal-sys-code for code

**Comment by alias-rahil** [comment]
@all-contributors please add @Vishal-sys-code for code

**Pull request merged**
